#222 新 haro が追加済のチャンネルでは、新 haro に移植済のコマンドが呼ばれないようにする
beproud/beproudbot pull request #223
Opened 2021-12-16 07:25 UTC by posbin

## Issue
#222 

- #XX

このレビューで確認してほしい点

- [ ] foo bar
- [ ] hoge fuga

レビューチェックリスト

- [ ] C2 体を表す名前の公理：あらかじめ決められている以外の汎用的な名前のモジュールを作らない
- [ ] C3 汎用名のモジュール内に長々と具体的処理を書かない
- [ ] C4 単純な処理の長さで分割しない
- [ ] C5 引数の数を減らす
- [ ] C6 パッケージ間で共通した定数を作らない
- [ ] C7 継承の利用を最小限にする
- [ ] C8 親クラスのテストを子クラスでも実行すること
- [ ] C9 オーバーライドを減らす
- [ ] C10 継承やオーバーライドを明示する

2022-01-20 03:33 UTC, wanshot requested changes
一点だけ指摘しました、その他はLGTMです。

2022-01-20 03:33 UTC, wanshot commented on src/haro/decorators.py
> +            cinfo = webapi.conversations.members(channel)
デフォルトだと100名しか取ってこないので `next_cursor` をチェックした方がよさそうです。(random部屋は143名)
https://api.slack.com/methods/conversations.members#arg_limit

2022-01-20 05:31 UTC, posbin commented on src/haro/decorators.py
> +                cinfo = webapi.conversations.members(channel, cursor)
cursor はデフォルトでは None
https://github.com/os/slacker/blob/3c7f43f75ee838be1121342c1aea1360388015e8/slacker/__init__.py#L221

2022-01-20 05:32 UTC, posbin commented on src/haro/decorators.py
> +            # next_cursor がレスポンスに存在しない場合、NULLの場合、空の場合は、以降の結果がないので取得完了
このコメントは以下ページに書かれてあったことを参考

https://api.slack.com/docs/pagination

> An empty, null, or non-existent next_cursor in the response indicates no further results.

2022-02-17 00:45 UTC, wanshot approved these changes
LGTM :tada:

2022-10-20 06:56 UTC, merged